### ISSUE TITLE
Does this work with STMPE811?

### ISSUE THREAD

**Issue by justcallmekoko** [adafruit/Adafruit_CircuitPython_STMPE610#14]
I would like to use this library with an [Adafruit 3.5" Pi TFT Display](https://www.adafruit.com/product/2441) on my raspberry pi.

As shown in the picture, this product uses an STMPE811 even though the silkscreen on the board says is has an STMPE610.
![image](https://user-images.githubusercontent.com/25190487/94691458-50c5fa00-02ff-11eb-9f46-c940dae06af1.png)

Will this library still work? I am not sure how much variation there is between the STMPE ICs.

**Comment by ladyada** [comment]
yes it would work, but why are you not using the kernel driver tutorial, it adds native support

**Comment by justcallmekoko** [comment]
@ladyada I will look into the kernel driver tutorial as I am not familiar with it yet. I just want to make sure I will be able to write a python script that will allow me to read touch inputs on this screen using that specific touch controller. As you can probably tell from my issue posts, I am going down a bit of a rabbit hole.

Would you be able to provide a link to the kernel driver tutorial you are referencing. I want to make sure I read the correct one.

I am not looking to display the pi desktop or console on the TFT display but rather my own user interface from a python script while also reading touch input.

**Comment by ladyada** [comment]
https://learn.adafruit.com/adafruit-pitft-3-dot-5-touch-screen-for-raspberry-pi

for tech support, please use the adafruit forums. github is for code bug reports
