### ISSUE TITLE
documentation doesn't match the .py source

### ISSUE THREAD

**Issue by CedarGroveStudios** [adafruit/Adafruit_CircuitPython_STMPE610#24]
The documentation content didn't update with PR#22. Is there a way to see where the documentation needs to be fixed?

https://github.com/adafruit/Adafruit_CircuitPython_STMPE610/pull/22

**Comment by FoamyGuy** [comment]
I think the build failure log is here for the most recent attempt: https://readthedocs.org/projects/adafruit-circuitpython-stmpe610/builds/15990417/ 

I think it boils down to readthe docs expecting a different syntax for how we declare which python version will be used to build the docs inside of their system.

**Comment by FoamyGuy** [comment]
I think a change like this will be the fix for it: https://github.com/adafruit/Adafruit_CircuitPython_AzureIoT/pull/40/files

**Comment by tekktrik** [comment]
@FoamyGuy it looks like the documentation is now building, is this resolved with the patch by @evaherrada?

**Comment by CedarGroveStudios** [comment]
The documentation looks okay now. Thanks!
